### ISSUE TITLE
 No 20.7 archetype found anywhere

### ISSUE THREAD

**Issue by ejemba** [seedstack/seedstack-maven-plugin#9]
Hi here is the warning I have when trying the plugin right now 

![image](https://user-images.githubusercontent.com/887400/90450064-130f6800-e0e9-11ea-9767-44c2d8720907.png)

Best regards

**Comment by adrienlauer** [comment]
Hi!
Fixed by commit e15c12a9b945d38eda3b3409c118a575cfdaceaf in seedstack/website
